routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthCtrl;
use App\Http\Controllers\AppSettingsCtrl;
use App\Http\Controllers\UrlCtrl;
use App\Http\Controllers\RoleCtrl;
use App\Http\Controllers\PermissionsCtrl;
use App\Http\Controllers\RegisterCtrl;
use App\Http\Controllers\BerandaCtrl;
use App\Http\Controllers\BlogsCtrl;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return redirect('login');
});
Route::get('login', [AuthCtrl::class, 'index'])->name('login');
Route::post('signin',[AuthCtrl::class,'login'])->name('auth.login');
Route::get('/daftar',[RegisterCtrl::class,'daftar'])->name('daftar');
Route::get('/daftar/pegawai',[RegisterCtrl::class,'daftarPegawai'])->name('daftar.pegawai');
Route::post('/daftar/pegawai',[RegisterCtrl::class,'checkDaftarPegawai'])->name('daftar.pegawai.check');

Route::get('/register/create-account/verify/{id}/{token}',[RegisterCtrl::class,'verifyRegister'])->name('daftar.buat-akun');
Route::post('/register/create-account/verify/{id}/{token}',[RegisterCtrl::class,'verifyRegisterNow'])->name('daftar.buat-akun.sekarang');

Route::get('/getcities/{id}', [BerandaCtrl::class,'getCities'])->name('getcities');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::group(['prefix' => 'app','as' => 'app.'],function(){
            
        Route::get('/',[BerandaCtrl::class,'index'])->name('beranda');
        Route::get('/beranda',[BerandaCtrl::class,'index'])->name('beranda.index');

        Route::match(['GET','POST'],'app-settings', [AppSettingsCtrl::class,'index'])->name('app_setting');

        Route::resource('/url',UrlCtrl::class);
        Route::get('url/delete/{id}', [UrlCtrl::class,'destroy']);

        Route::resource('/permissions',PermissionsCtrl::class);
        Route::get('permissions/delete/{id}', [PermissionsCtrl::class,'destroy']);
        Route::get('permissions/generate/{id}', [PermissionsCtrl::class,'generate']);

        Route::resource('/role',RoleCtrl::class);
        Route::get('role/delete/{id}', [RoleCtrl::class,'destroy']);
        Route::match(array('GET','POST'),'/role/configuration-permissions/{id}', [RoleCtrl::class,'permission']);
        Route::match(array('GET','POST'),'/role/configuration-menus/{id}', [RoleCtrl::class,'menu']);

        Route::resource('/blogs',BlogsCtrl::class);
        Route::get('blogs/delete/{id}', [BlogsCtrl::class,'destroy']);

        Route::get('/signout',[AuthCtrl::class,'signout'])->name('auth.logout');
    });
});

app/Models/Blogs.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use App\Traits\Uuid;

class Blogs extends Model
{
    use Uuid;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'blogs';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';
    
    public $incrementing = false;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'image_name',
        'image_path',
        'created_by',
        'updated_by',

    ];

    public function comments()
    {   
        return $this->hasMany(CommentBlogs::class, 'blog_id')->orderBy('created_at', 'desc');
    }
}

resources/views/blogs/create.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="container-fluid p-0">
    <div class="mb-3">
        <h1 class="h3 d-inline align-middle"><strong>{{$title}}</strong></h1>
        <a class="badge bg-dark text-white ms-2" href="{{ route('app.blogs.index') }}">
            < Kembali
        </a>
    </div>
    <form id="form">
        <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
        @csrf
        <div class="row">
            <div class="col-md-12">
                <!--begin::Card-->
                <div class="card card-custom gutter-b example example-compact">
                    <div class="card-header">
                        <h3 class="card-title">Hotel Detail</h3>
                    </div>
                    <div class="card-body">
                        <div class="validation-message"></div>
                        @include ('components.caution', ['title' => $title])
                        @include ('blogs.form', ['formMode' => 'create'])
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Ubah Data' : 'Tambah Baru' }}</button>
            <a href="{{ route('app.blogs.index') }}" class="btn btn-danger mr-2">Kembali</a>
        </div>
    </form>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
            document.getElementById('form'),
            {
                fields: {
                    title: {
                        validators: {
                            notEmpty: {
                                message: 'Title!'
                            },
                            stringLength: {
                                max:225,
                                message: 'Maximum is 225 characters.'
                            }
                        }
                    },
                    description: {
                        validators: {
                            notEmpty: {
                                message: 'description!'
                            }
                        }
                    },
                    @if($edit == false)
                    image: {
                        validators: {
                            notEmpty: {
                                message: 'Image!'
                            }
                        }
                    }
                    @endif
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
        ).on('core.form.valid', function() {
            var formData = $("#form").serialize();
            showLoading();
            $.ajax({
                url: "{{ $edit == true ? route('app.blogs.update',[app('request')->blog]) : route('app.blogs.store') }}",
                type: "POST",
                dataType: "JSON",
                data: new FormData($('#form')[0]),
                processData: false,
                contentType: false,
                success: function (data)
                {
                    Swal.fire("Berhasil!", "{{ $edit == true ? 'Successfully changed data blogs!' : 'New blogs data added successfully!' }}", "success");
                    hideLoading();
                    window.location.href = "{{ route('app.blogs.index') }}";
                },
                error: function (xhr, status, error)
                {
                    var errs = '<ul style="display:block">'
                    if(xhr.status == 422){
                        p = xhr.responseJSON.errors;
                        for(var key in p){
                            p[key].forEach(err => {
                                errs += '<li><label class="error">'+err+'</label></li>'
                            })
                        }
                        errs += '</ul>';
                    }else{
                        errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                    }
                    $('.validation-message').html(errs)
                    hideLoading()
                }
            });
        });
    });

    var image1 = new KTImageInput('kt_image_1');

</script>
@endsection

resources/views/blogs/form.blade.php
<div class="form-group">
    <label>Title<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="title" id="title" value="{{ isset($data->title) ? $data->title : ''}}" required>
</div>
<div class="form-group">
    <label>Description<span class="text-danger">*</span></label>
    <textarea name="description" class="form-control">{{isset($data->description) ? $data->description : ''}}</textarea>
</div>

<div class="form-group row">
    <label>Image <span class="text-danger">*</span></label>
    <div class="col-lg-9 col-xl-6">
        <div class="image-input image-input-outline" id="kt_image_1">
            <div class="image-input-wrapper" style="background-image: url(//{{ isset($data) ? $data->image_path.'/'.$data->image_name : '' }})"></div>
            <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                <i class="fa fa-pen icon-sm text-muted"></i>
                <input type="file" name="image" accept=".png, .jpg, .jpeg"/>
                <input type="hidden" name="image_remove"/>
            </label>

            <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                <i class="ki ki-bold-close icon-xs text-muted"></i>
            </span>
        </div>
        <span class="form-text text-muted">Allowed file types:  png, jpg, jpeg.</span>
    </div>
</div>

resources/views/blogs/index.blade.php
@extends('components.template')
@section('title',__($title))
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-12 col-lg-12">
                <div class="card card-custom gutter-b example example-compact">
                {{kt_datatable('Data '.$title, Request::url())}}
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
<script>
var KTDatatableJsonRemoteDemo = function() {
    var dataTable = function() {
        var datatable = $('#kt_datatable').KTDatatable({
            data: {
                type: 'remote',
                source: {
                    read : {
                        method: 'GET',
                        url: '{{ route('app.blogs.index') }}',
                    }
                },
                pageSize: 10,
            },
            layout: {
                scroll: false,
                footer: false
            },

            sortable: true,
            pagination: true,
            search: {
                input: $('#kt_datatable_search_query'),
                key: 'generalSearch'
            },
            columns: [
            {
                field: 'Actions',
                title: 'Actions',
                sortable: false,
                autoHide: false,
                width : 70,
                overflow: 'visible',
                template: function(data, type, full, meta) {
                        return '\
                        <div class="d-flex align-items-center">\
                        </div>\
                        <div class="dropdown dropdown-inline">\
                            <a href="javascript:;" class="btn btn-sm btn-clean btn-icon mr-2" data-toggle="dropdown">\
                                <span class="svg-icon svg-icon-md">\
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">\
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">\
                                            <rect x="0" y="0" width="24" height="24"/>\
                                            <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"/>\
                                        </g>\
                                    </svg>\
                                </span>\
                            </a>\
                            <div class="dropdown-menu dropdown-menu-md dropdown-menu-left">\
                                <ul class="navi flex-column navi-hover py-2">\
                                    <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">\
                                        Choose an action:\
                                    </li>\
                                    <li class="navi-item">\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'/edit" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-edit"></i></span>\
                                            <span class="navi-text">Edit</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-search"></i></span>\
                                            <span class="navi-text">View</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/delete/")}}'+data.id+'" class="navi-link btn-delete-on-table">\
                                            <span class="navi-icon"><i class="la la-trash"></i></span>\
                                            <span class="navi-text">Delete</span>\
                                        </a>\
                                    </li>\
                                </ul>\
                            </div>\
                        </div>\
                    ';
                },
            },
            {
                field: 'title',
                title: 'Title',
            },
            {
                field: 'created_at',
                title: 'Created',
                template: function(row) {
                    return row.created_at ? Utils.dateIndonesia(row.created_at,true,true) : '-';
                },
            },
            {
                field: 'updated_at',
                title: 'Updated',
                template: function(row) {
                    return row.updated_at ? Utils.dateIndonesia(row.updated_at,true,true) : '-';
                },
            }
            ],
        });
    };

    return {
        init: function() {
            dataTable();
        }
    };
}();

jQuery(document).ready(function() {
    KTDatatableJsonRemoteDemo.init();
});

</script>
<script src="{{ URL::asset('assets/js/KtDatatableDelete.js') }}"></script>
<script src="{{ URL::asset('assets/js/KtDatatableProses.js') }}"></script>
@endsection

resources/views/blogs/view.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="container-fluid p-0">
    @include('components.alert')
    <div class="mb-3">
        <h1 class="h3 d-inline align-middle"><strong>{{$title}}</strong></h1>
        <a class="badge bg-dark text-white ms-2" href="{{ route('app.blogs.index') }}">
            < Kembali
        </a>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">
                        City&nbsp;
                    </h3>
                </div>
                <div class="card-body row">
                    <div class="col-md-7">
                        <table border="0" class="table-vertical-top">
                            <tr>
                                <th>Title</th>
                                <th> : </th>
                                <td>{{$data->title}}</td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <th> : </th>
                                <td>{{$data->description}}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-5">
                        <div class="mb-3">
                            <label class="form-label">Main Image : </label></br>
                            <img src="http://{{$data->image_path.'/thumbnail/'.$data->image_name }}" style="max-width: 200px">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection