routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthCtrl;
use App\Http\Controllers\AppSettingsCtrl;
use App\Http\Controllers\UrlCtrl;
use App\Http\Controllers\RoleCtrl;
use App\Http\Controllers\PermissionsCtrl;
use App\Http\Controllers\RegisterCtrl;
use App\Http\Controllers\BerandaCtrl;
use App\Http\Controllers\BlogsCtrl;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return redirect('login');
});
Route::get('login', [AuthCtrl::class, 'index'])->name('login');
Route::post('signin',[AuthCtrl::class,'login'])->name('auth.login');
Route::get('/daftar',[RegisterCtrl::class,'daftar'])->name('daftar');
Route::get('/daftar/pegawai',[RegisterCtrl::class,'daftarPegawai'])->name('daftar.pegawai');
Route::post('/daftar/pegawai',[RegisterCtrl::class,'checkDaftarPegawai'])->name('daftar.pegawai.check');

Route::get('/register/create-account/verify/{id}/{token}',[RegisterCtrl::class,'verifyRegister'])->name('daftar.buat-akun');
Route::post('/register/create-account/verify/{id}/{token}',[RegisterCtrl::class,'verifyRegisterNow'])->name('daftar.buat-akun.sekarang');

Route::get('/getcities/{id}', [BerandaCtrl::class,'getCities'])->name('getcities');

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::group(['prefix' => 'app','as' => 'app.'],function(){
            
        Route::get('/',[BerandaCtrl::class,'index'])->name('beranda');
        Route::get('/beranda',[BerandaCtrl::class,'index'])->name('beranda.index');

        Route::match(['GET','POST'],'app-settings', [AppSettingsCtrl::class,'index'])->name('app_setting');

        Route::resource('/url',UrlCtrl::class);
        Route::get('url/delete/{id}', [UrlCtrl::class,'destroy']);

        Route::resource('/permissions',PermissionsCtrl::class);
        Route::get('permissions/delete/{id}', [PermissionsCtrl::class,'destroy']);
        Route::get('permissions/generate/{id}', [PermissionsCtrl::class,'generate']);

        Route::resource('/role',RoleCtrl::class);
        Route::get('role/delete/{id}', [RoleCtrl::class,'destroy']);
        Route::match(array('GET','POST'),'/role/configuration-permissions/{id}', [RoleCtrl::class,'permission']);
        Route::match(array('GET','POST'),'/role/configuration-menus/{id}', [RoleCtrl::class,'menu']);

        Route::resource('/blogs',BlogsCtrl::class);
        Route::get('blogs/delete/{id}', [BlogsCtrl::class,'destroy']);

        Route::get('/signout',[AuthCtrl::class,'signout'])->name('auth.logout');
    });
});

app/Models/Url.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use App\Traits\Uuid;
use Illuminate\Database\Eloquent\Model;

class Url extends Model
{
    use Uuid;
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'url';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['parent_id','url','name','icon','order','position'];

    public $incrementing = false;
    
    public function children()
    {   
        return $this->hasMany(self::class,'parent_id')->orderBy('order','asc')
                ->select('url.id','url.parent_id','url.url','url.icon','url.position','url.name')
                ->join('url_access','url_access.url_id','url.id')
                ->join('users','users.role_id','url_access.role_id')
                ->where('users.id', Auth::user()->id);
    }

    public function parent()
    {   
        return $this->belongsTo(self::class,'parent_id');
    }
}

resources/views/settings/url/create.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-md-12">
            <!--begin::Card-->
            <div class="card card-custom gutter-b example example-compact">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                    <div class="card-toolbar">
                        <div class="example-tools justify-content-center">
                            <a href="{{ route('app.url.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Kembali</a>
                        </div>
                    </div>
                </div>
                <form id="form">
                    <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                    @csrf
                    <div class="card-body">
                        <div class="validation-message"></div>
                        @include ('components.caution', ['title' => $title])
                        @include ('settings.url.form', ['formMode' => 'create'])
                    </div>
                    <div class="card-footer">
                        <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Ubah url' : 'Tambah Baru' }}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
         document.getElementById('form'),
         {
            fields: {
               parent_id: {
                  validators: {
                     stringLength: {
                        max:36,
                        message: 'Maksimal adalah 36 angka/karakter.'
                    }
                }
            },
            nama: {
              validators: {
                 notEmpty: {
                    message: 'Nama Url!'
                },
                stringLength: {
                    max:25,
                    message: 'Maksimal adalah 25 karakter.'
                }
            }
        },
        url: {
            validators: {
                notEmpty: {
                    message: 'Url!'
                },
                stringLength: {
                    max:25,
                    message: 'Maksimal adalah 25 karakter.'
                }
            }
        },
        url: {
            validators: {
                stringLength: {
                    max:500,
                    message: 'Maksimal adalah 500 karakter.'
                }
            }
        },
        order: {
          validators: {
             intLength: {
                max:11,
                message: 'Maksimal adalah 11 angka/karakter.'
            }
        }
    },
    position: {
      validators: {
        notEmpty: {
            message: 'Position!'
        },
        stringLength: {
            max:25,
            message: 'Maksimal adalah 25 karakter.'
        }
    }
}
},
plugins:{
    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
            ).on('core.form.valid', function() {
                var formData = $("#form").serialize();
                showLoading();
                $.post('{{ $edit == true ? route('app.url.update',[app('request')->url])  : route('app.url.store') }}', formData)
                .done(function(data){
                    Swal.fire("Berhasil!", "{{ $edit == true ? 'Berhasil merubah data url!' : 'Data url baru berhasil ditambahkan!' }}", "success");
                    hideLoading();
                    window.location.href = "{{ route('app.url.index') }}";
                }).fail(function(xhr,status,error){
                    var errs = '<ul style="display:block">'
                    if(xhr.status == 422){
                        p = xhr.responseJSON.errors;
                        for(var key in p){
                            p[key].forEach(err => {
                                errs += '<li><label class="error">'+err+'</label></li>'
                            })
                        }
                        errs += '</ul>';
                    }else{
                        errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                    }
                    $('.validation-message').html(errs)
                    hideLoading()
                });
            });
        });
    </script>
    @endsection

resources/views/settings/url/edit.blade.php
@extends('components.template')
@section('title',$title)
@section('content')
<div class="main d-flex flex-column flex-row-fluid">
    @include('components.breadcrumb')
    <div class="content flex-column-fluid" id="kt_content">
        <div class="row">
            <div class="col-md-12">
                <!--begin::Card-->
                <div class="card card-custom gutter-b example example-compact">
                    <div class="card-header">
                        <h3 class="card-title">{{$title}}</h3>
                        <div class="card-toolbar">
                            <div class="example-tools justify-content-center">
                                <a href="{{ route('app.url.index') }}" class="btn btn-info"><i class="ki ki-long-arrow-back"></i> Kembali</a>
                            </div>
                        </div>
                    </div>
                    <form id="form">
                        <input type="hidden" name="_method" value="{{ $edit == true ? 'PATCH' : 'POST' }}">
                        {{ method_field('PATCH') }}
                        @csrf
                        <div class="card-body">
                            <div class="validation-message"></div>
                            @include ('components.caution', ['title' => $title])
                            @include ('settings.url.form', ['formMode' => 'create'])
                        </div>
                        <div class="card-footer">
                            <button type="submit" id="submit" class="btn btn-primary mr-2">{{ $edit == true ? 'Ubah url' : 'Tambah Baru' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
        const fv = FormValidation.formValidation(
			document.getElementById('form'),
			{
				fields: {
					parent_id: {
						validators: {
							stringLength: {
								max:36,
								message: 'Maksimal adalah 36 angka/karakter.'
							}
						}
					},
					nama: {
						validators: {
							notEmpty: {
								message: 'Nama Url!'
							},
							stringLength: {
								max:25,
								message: 'Maksimal adalah 25 karakter.'
							}
						}
					},
                    url: {
                        validators: {
                            notEmpty: {
                                message: 'Url!'
                            },
                            stringLength: {
                                max:25,
                                message: 'Maksimal adalah 25 karakter.'
                            }
                        }
                    },
                    url: {
                        validators: {
                            stringLength: {
                                max:500,
                                message: 'Maksimal adalah 500 karakter.'
                            }
                        }
                    },
					order: {
						validators: {
							intLength: {
								max:11,
								message: 'Maksimal adalah 11 angka/karakter.'
							}
						}
					},
					position: {
						validators: {
                            notEmpty: {
                                message: 'Position!'
                            },
							stringLength: {
								max:25,
								message: 'Maksimal adalah 25 karakter.'
							}
						}
					}
                },
                plugins:{
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    SubmitButton: new FormValidation.plugins.SubmitButton()
                }
            }
        ).on('core.form.valid', function() {
            var formData = $("#form").serialize();
            showLoading();
            $.post('{{ $edit == true ? route('app.url.update',[app('request')->url])  : route('app.url.store') }}', formData)
            .done(function(data){
                Swal.fire("Berhasil!", "{{ $edit == true ? 'Berhasil merubah data url!' : 'Data url baru berhasil ditambahkan!' }}", "success");
                hideLoading();
                window.location.href = "{{ route('app.url.index') }}";
            }).fail(function(xhr,status,error){
                var errs = '<ul style="display:block">'
                if(xhr.status == 422){
                    p = xhr.responseJSON.errors;
                    for(var key in p){
                        p[key].forEach(err => {
                            errs += '<li><label class="error">'+err+'</label></li>'
                        })
                    }
                    errs += '</ul>';
                }else{
                    errs += '<li><label class="error">'+xhr.responseJSON.message+'</label></li>';
                }
                $('.validation-message').html(errs)
                hideLoading()
            });
        });
    });
</script>
@endsection

resources/views/settings/url/form.blade.php
<div class="form-group">
    <label>Parent</label>
    <select class="form-control" name="parent_id" id="parent_id">
        <option> </option>
        @foreach($parent as $val)
        <option value="{{$val->id}}" {{ isset($url->parent_id) ? $url->parent_id == $val->id ? 'selected' : '' : '' }}>{{$val->name}}</option>
        @endforeach
    </select>
    <span class="form-text text-muted">Pilih apabila memiliki induk</span>
</div>
<div class="form-group">
    <label>Nama<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="name" id="name" value="{{ isset($url->name) ? $url->name : ''}}" >
</div>
<div class="form-group">
    <label>Url<span class="text-danger">*</span></label>
    <input type="text" class="form-control" name="url" id="url" value="{{ isset($url->url) ? $url->url : ''}}" >
</div>
<div class="form-group">
    <label>Icon</label>
    <textarea class="form-control" name="icon" rows="3" placeholder="icon url">{{ $edit == true ? $url->icon : old('icon') }}</textarea>
</div>
<div class="form-group">
    <label>Order<span class="text-danger">*</span></label>
    <input type="number" class="form-control" name="order" id="order" value="{{ isset($url->order) ? $url->order : ''}}" >
</div>
<div class="form-group">
    <label>Position<span class="text-danger">*</span></label>
    <select class="form-control" name="position" id="position">
        <?php if (isset($url->position)) { ?>
        <option value="{{$url->position}}">{{$url->position}}</option>
        <?php } ?>
        <option> </option>
        <option value="settings">Settings</option>
        <option value="master">Master</option>
        <option value="menu utama">Menu Utama</option>
    </select>
</div>

resources/views/settings/url/index.blade.php
@extends('components.template')
@section('title',__($title))
@section('content')
<div class="container-fluid p-0">
    <div class="row">
        <div class="col-12 col-lg-12">
                <div class="card card-custom gutter-b example example-compact">
                {{kt_datatable('Data '.$title, Request::url())}}
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
<script>
var KTDatatableJsonRemoteDemo = function() {
    var dataTable = function() {
        var datatable = $('#kt_datatable').KTDatatable({
            data: {
                type: 'remote',
                source: {
                    read : {
                        method: 'GET',
                        url: '{{ route('app.url.index') }}',
                    }
                },
                pageSize: 10,
            },
            layout: {
                scroll: false,
                footer: false
            },

            sortable: true,
            pagination: true,
            search: {
                input: $('#kt_datatable_search_query'),
                key: 'generalSearch'
            },
            columns: [
            {
                field: 'Actions',
                title: 'Actions',
                sortable: false,
                autoHide: false,
                width : 70,
                overflow: 'visible',
                template: function(data, type, full, meta) {
                        return '\
                        <div class="d-flex align-items-center">\
                        </div>\
                        <div class="dropdown dropdown-inline">\
                            <a href="javascript:;" class="btn btn-sm btn-clean btn-icon mr-2" data-toggle="dropdown">\
                                <span class="svg-icon svg-icon-md">\
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">\
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">\
                                            <rect x="0" y="0" width="24" height="24"/>\
                                            <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"/>\
                                        </g>\
                                    </svg>\
                                </span>\
                            </a>\
                            <div class="dropdown-menu dropdown-menu-md dropdown-menu-left">\
                                <ul class="navi flex-column navi-hover py-2">\
                                    <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">\
                                        Choose an action:\
                                    </li>\
                                    <li class="navi-item">\
                                        <a href="{{url(Request::url()."/")}}'+data.id+'/edit" class="navi-link">\
                                            <span class="navi-icon"><i class="la la-edit"></i></span>\
                                            <span class="navi-text">Edit</span>\
                                        </a>\
                                        <a href="{{url("app/permissions/generate")}}/'+data.id+'" class="navi-link btn-proses-on-table">\
                                            <span class="navi-icon"><i class="la la-gear"></i></span>\
                                            <span class="navi-text">Generate Permission</span>\
                                        </a>\
                                        <a href="{{url(Request::url()."/delete/")}}'+data.id+'" class="navi-link btn-delete-on-table">\
                                            <span class="navi-icon"><i class="la la-trash"></i></span>\
                                            <span class="navi-text">Delete</span>\
                                        </a>\
                                    </li>\
                                </ul>\
                            </div>\
                        </div>\
                    ';
                },
            },
            {
                field: 'parent_id',
                title: 'Parent',
                template: function(row) {
                    return row.parent ? row.parent.name : '-';
                },
            },
            {
                field: 'url',
                title: 'Url',
            },
            {
                field: 'name',
                title: 'Nama',
            },
            {
                field: 'icon',
                title: 'Icon',
            },
            {
                field: 'order',
                title: 'Order',
            },
            {
                field: 'position',
                title: 'Position',
            },
            {
                field: 'created_at',
                title: 'Created',
                template: function(row) {
                    return row.created_at ? Utils.dateIndonesia(row.created_at,true,true) : '-';
                },
            },
            {
                field: 'updated_at',
                title: 'Updated',
                template: function(row) {
                    return row.updated_at ? Utils.dateIndonesia(row.updated_at,true,true) : '-';
                },
            }
            ],
        });
    };

    return {
        init: function() {
            dataTable();
        }
    };
}();

jQuery(document).ready(function() {
    KTDatatableJsonRemoteDemo.init();
});

</script>
<script src="{{ URL::asset('assets/js/KtDatatableDelete.js') }}"></script>
<script src="{{ URL::asset('assets/js/KtDatatableProses.js') }}"></script>
@endsection